version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A django_credit_check worker -l info
    volumes:
      - .:/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery
