services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 1337:8000
    depends_on:
      - redis

  celery:
    build: ./project
    command: celery -A django_credit_check worker -l info
    volumes:
      - ./project:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./project
    command: flower -A core --port=5555 --broker=redis://localhost:6379
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery